apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-mtaylor-io
spec:
  template:
    spec:
      containers:
      - name: status-mtaylor-io
        image: images.home.mtaylor.io/status.mtaylor.io
        ports:
        - name: http
          protocol: TCP
          containerPort: 3000
